name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Specify Node.js version 16.x only

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Cache npm dependencies

    - name: Install dependencies
      run: npm ci  # Clean install dependencies

    - name: Run tests
      run: npm test  # Run tests (modify if you have tests)

    - name: Start the server
      run: npm start &  # Start the Express app in the background

    - name: Wait for the server to be ready
      run: sleep 10  # Wait for the server to be ready (adjust timing if necessary)

    - name: Test the server
      run: curl http://localhost:3500  # Send a request to your Express app

    - name: Shutdown the server
      run: kill $(lsof -t -i:3500)  # Kill the server after testing
